version: "3.3"
services:
  web:
    build: .
    volumes:
      - ".:/app"
    ports:
      - "3200:3200"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  mongo:
    build: ./mongo
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo_data:
  node_modules: